# Project information

site_name: 'Le site du Balrog'
site_description: 'Site WEB de démo pour Balrog'
site_author: 'Goffi'
site_url: 'https://balrog.goffinet.org/'
google_analytics:
  - 'UA-21733018-12'
  - 'auto'
copyright: 'Copyright &copy; 2017 Goffi'

# Theme

theme_dir: 'material/'
theme: 'material'

# Options

extra:
  language: fr
  feature:
    tabs: true
  palette:
    primary: 'red'
    accent: 'purple'
  disqus: 'www-goffinet-org'
  logo:
    icon: 'school'
  social:
    - type: 'github'
      link: 'https://github.com/goffinet'
    - type: 'twitter'
      link: 'https://twitter.com/fegoffinet'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/fegoffinet/'
    - type: 'building-o'
      link : 'https://www.goffinet.org'
    - type: 'book'
      link : 'https://biblio.goffinet.org'

# Extensions

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Content structure

pages:
- 'Le site du Balrog': 'index.md'
